source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftUtils_Example', :exclusive => true do
  pod "SwiftUtils", :path => "../"
end

target 'SwiftUtils_Tests', :exclusive => true do
  pod "SwiftUtils", :path => "../"

  
end
